export const SEARCH_DO_SEARCH_BEGIN = 'SEARCH_DO_SEARCH_BEGIN';
export const SEARCH_DO_SEARCH_SUCCESS = 'SEARCH_DO_SEARCH_SUCCESS';
export const SEARCH_DO_SEARCH_FAILURE = 'SEARCH_DO_SEARCH_FAILURE';
export const SEARCH_DO_SEARCH_DISMISS_ERROR = 'SEARCH_DO_SEARCH_DISMISS_ERROR';
