export const SEARCH_HANDLE_SUBMIT_BEGIN = 'SEARCH_HANDLE_SUBMIT_BEGIN';
export const SEARCH_HANDLE_SUBMIT_SUCCESS = 'SEARCH_HANDLE_SUBMIT_SUCCESS';
export const SEARCH_HANDLE_SUBMIT_FAILURE = 'SEARCH_HANDLE_SUBMIT_FAILURE';
export const SEARCH_HANDLE_SUBMIT_DISMISS_ERROR = 'SEARCH_HANDLE_SUBMIT_DISMISS_ERROR';
